### ISSUE TITLE
Adding more tests to cover cases of Nested Containers and multi-level drops.

### ISSUE THREAD

**Issue by jackdewinter** [jackdewinter/pymarkdown#1233]
## Prerequisites

* [X] Are you running the latest version of this application?
* [X] Have you checked the [Frequently Asked Questions](https://pymarkdown.readthedocs.io/en/latest/faq) document?
* [X] Did you perform a cursory search of other issues to look for related issues?

### Description

In going through the last batch of tests, noticed that the "dropping" scenarios (where we drop 2+ levels) had little coverage, both from a parsing POV and a rule Md031 POV.

### Desired Behavior of Feature

This should be handled properly, both by the parser and by rule Md031.

### What Are the Benefits of This Feature?

Ensure that users do not hit weird corner cases when scanning or fixing documents.

## Sub-Issues

- [1234](https://github.com/jackdewinter/pymarkdown/issues/1234)
- [1235](https://github.com/jackdewinter/pymarkdown/issues/1235)
